apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    metadata:
      name: test
    spec:
      containers:
      - name: test
        image: henrod/controller:v4
      restartPolicy: OnFailure
