language: go
go:
- 1.8
env:
  global:
  - secure: ffPgvKFwEwCFxOuVXbbrgFXCZ38iWnqnwf3cMcZpkKqAnJozzRT4d5JOgWg5CK/5mdi6ENn6VE1ZfPpFtk68spWYRCG3pQ4fq7neYJk1mgsvcIAg+iKNgvyZNSaNV74Ku/2VdV3XRm5Agfy3DMGsuPWv1g9Xu3JKqYt7pWVCn2Sa6U5C52QjnfAQnzhKEKuY2fIChfmorpZZA1PH12AYDKD74KtesjyuTJeGi7BcAUzbYo+ZN+Y3jj0Dq0h9nMCe0cbtV3afWgglWznQSEc3dLXPO2H9wuLoh/RE7afkDjEeq2r2Jd4L5vUg5x0ydIHrKAjmsJJ6jo5KJd9xbnR+Q9yqWTmt8ZkaUBE6VTqAveju4JCXqIdfc6fxcWW2o7EKeJkYN8zu+RQiIJXiek0ik18hcLpKyaFzULluDzWkctZtzfxQ7xH8D0jkBsD3+IAQGBzoW5faBhP80aj+MfwGumFJlkIN0xj+6mWTFOFyBb0FbH2ka6Xf2z7uXf4cwoR+UbJNNvoXTb1/AgJ9NuoO3Z9kGC+9M7BhPFt0egLtVldFPDbd4ej6VMJmAGllqYvZ2qdx5xb3XS1kf2P5rteFBhKUJfw8BNFKltgfm+XFmH66G4LAmSfcNyFUkUgaItdszNdYvJTVciy1Ch0wk+DmJDPyQzjOLoLrkSqJtGudSAI=
  - secure: QHoeeBnLEz0ar8/HB47MmY0J4znLfFsx6jf8Gwrqh0Dv/3tIT28opPsHDE+Uq6ucoU2RhwEWqOy7QTl2MDBBTe6pqRuf/m7EcCrrb3YZi5rEPvsr+gyww7A/MxLcYkYX+56lSVvOAe1Y+Mn83SBFUEZPKDjLgJtgShrT5IKP/IgTf2ZZMPqLKc+1m/aANjnwDbKr/pOcU/bwnNRqvHOhNIZFUssFqXMM+CzoyeBK5vGJXL5xpEoNDuf6OACRI7rwLsDM72nT2oIABsF8pDTTF5PMomE4gaxKO4NnrspiNhID+CjwodtD+6gMG5rzr76pOaNED9vEbQUjxaOR9cWxAicVVUjJq+l3RoLSbonGvcuccOf5CxSZsv+CLryG69jS7djYI2z7V1/sfDARnh/W8zeC2sQ4S9B9SDCdrslnGgE/d81WOYec/J144uGNZCsIjuKOcJv9FlaVL3Wxulqniqmz27Ir4CSDsKP8gLjShaBWV5J4CVA6T/gkXDX8KMZs/UixRIDgh+Dz/O3H2yNqdA1BmhCnkz7kHl+QD7yl8emuQunDbT+Vi7kfNHygCVQmWcsyo6QvXCB7QOrWyOUEgvVRQL/lpF+K/5HbcIWjWLZQtATBkz/Su8MEXK9itTOrvGJP5mUAD/4i3uUucgTKfbMXNKjSPPT2n19cWf7ZnYs=
services:
- docker
sudo: true
install:
- make setup-ci
script:
- make test
after_success: bash after-success.sh
