# mystack-controller api
# https://github.com/topfreegames/mystack-controller
#
# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright © 2017 Top Free Games <backend@tfgco.com>

apiVersion: v1
kind: Service
metadata:
  name: mystack-controller
  namespace: mystack
spec:
  selector:
    app: mystack-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mystack-controller
  namespace: mystack
  labels:
    heritage: mystack
spec:
  selector:
    matchLabels:
      app: mystack-controller
      heritage: mystack
  replicas: 1
  template:
    metadata:
      labels:
        app: mystack-controller
        heritage: mystack
    spec:
      containers:
        - name: controller
          command:
            - /app/mystack-controller
            - start
            - -v3
          image: quay.io/tfgco/mystack-controller:v0.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSTACK_POSTGRES_HOST
              value: mystack-postgres
            - name: MYSTACK_POSTGRES_PORT
              value: "5432"
            - name: MYSTACK_POSTGRES_USER
              value: mystack
            - name: MYSTACK_POSTGRES_DBNAME
              value: mystack
            - name: MYSTACK_GOOGLE_CLIENT_ID
              value: ""
            - name: MYSTACK_GOOGLE_CLIENT_SECRET
              value: ""
            - name: MYSTACK_OAUTH_ACCEPTEDDOMAINS
              value: "example.com other.com"
