# mystack-controller api
# https://github.com/topfreegames/mystack-controller
#
# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright © 2017 Top Free Games <backend@tfgco.com>

apiVersion: v1
kind: Service
metadata:
  name: mystack-postgres
  namespace: mystack
spec:
  selector:
    app: mystack-postgres
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 5432
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mystack-postgres
  namespace: mystack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mystack-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.5
          ports:
            - containerPort: 5432
