---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mystack-postgres
  name: mystack-postgres
  namespace: mystack
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: mystack-postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mystack-postgres
  namespace: mystack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mystack-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        ports:
          - containerPort: 5432
        env:
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        - name: POSTGRES_USER
          value: mystack
        - name: POSTGRES_DB
          value: mystack
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP --username mystack
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readiness-probe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP --username mystack
          initialDelaySeconds: 5
          timeoutSeconds: 3
          period-seconds: 5
