postgres:
  user: "mystack_controller"
  dbName: "mystack_controller"
  host: "localhost"
  port: 8585
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10
oauth:
  acceptedDomains: 
  - "example.com"
  - "other.com"
  - "tfgco.com"
kubernetes:
  appsDomain:
    "kubernetes.example.com"
