postgres:
  user: "mystack_controller_test"
  dbName: "mystack_controller_test"
  host: "localhost"
  port: 8585
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10

oauth:
  enabled: true
  acceptedDomains: 
  - "example.com"
  - "other.com"

kubernetes:
  service-domain-suffix: mystack.com
  port-forward-tcp-port: 28000
  deployments:
    default:
      resources:
        limits:
          cpu: 10m
          memory: 300Mi
        requests:
          cpu: 5m
          memory: 100Mi
