postgres:
  user: "mystack_controller_test"
  dbName: "mystack_controller_test"
  host: "localhost"
  port: 8585
  sslMode: "disable"
  maxIdleConns: 10
  maxOpenConns: 10
email:
  domain: 
  - "tfgco.com"
  - "topfreegames.com"
